name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/my-keypair.pem
        chmod 600 ~/.ssh/my-keypair.pem

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to AWS EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i ~/.ssh/my-keypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        docker stop backend-app || true && docker rm backend-app || true
        docker stop frontend-app || true && docker rm frontend-app || true
        docker run -d -p 5000:5000 --name backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app
        docker run -d -p 80:80 --name frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app
        EOF

