name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Backend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app ./frontend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Backend Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app

    - name: Push Frontend Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app

    # Add a step to set up the SSH key
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/my-keypair.pem
        chmod 600 ~/.ssh/my-keypair.pem

    - name: Deploy to AWS EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i ~/.ssh/my-keypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        docker stop backend-app || true && docker rm backend-app || true
        docker stop frontend-app || true && docker rm frontend-app || true
        docker run -d -p 5000:5000 --name backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app
        docker run -d -p 80:80 --name frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app
        EOF

